repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check (src)
        entry: uv run ruff check src
        language: system
        pass_filenames: false

      - id: pylint-src
        name: pylint (src)
        entry: uv run pylint src
        language: system
        pass_filenames: false

      - id: mypy-src
        name: mypy (src)
        entry: uv run mypy src
        language: system
        pass_filenames: false
